In [1]:
import pandas as pd
import numpy as np
import haversine as hs

In [2]:
df = pd.read_csv('link_seoul_ver3.csv', encoding='cp949')
link = df['LINK_ID'].values
geometry = df['geometry']

geometry = geometry.str.replace('LINESTRING','')
geometry = geometry.str.replace('(','')
geometry = geometry.str.replace(')','')
geometry = geometry.str.replace(' ',',')
geometry = geometry.str.replace(',,',',')
geometry = geometry.str.split(',')
for i in range(len(geometry)):
    geometry[i].pop(0)

def distance(x1,y1,x2,y2,x3,y3):
    if x1 == x2:
        m = 0
    else:
        m = (y2-y1)/(x2-x1)
    a = m
    b = -1
    c = y1 - m*x1
    d = abs(a*x3 + b*y3 + c) / np.sqrt(a**2 + b**2)
    return d

def distance_link(link, geometry, x, y):
    d = []
    for i in range(0, len(geometry[link]) - 2, 2):
        x1 = float(geometry[link][i+1])
        y1 = float(geometry[link][i])
        x2 = float(geometry[link][i+3])
        y2 = float(geometry[link][i+2])
        d.append(distance(x1,y1,x2,y2,x,y))
    return min(d)

def distance_haversine(link, geometry, x, y):
    for i in range(len(geometry[link])):
        if i % 2 == 0:
            x1 = float(geometry[link][i+1])
            y1 = float(geometry[link][i])
            if hs.haversine((x,y),(x1,y1)) <= 0.3:
                return True
            else:
                continue
        else:
            continue
    

def link_haversine(geometry, x, y):
    link_haversine = []
    for i in range(len(geometry)):
        if distance_haversine(i,geometry,x,y) == True:
            link_haversine.append(i)
    return link_haversine

def link_shortest(link_haversine, geometry, x, y):
    d = []
    for i in range(len(link_haversine)):
        d.append(distance_link(link_haversine[i],geometry,x,y))
    if len(d) == 0:
        return None
    else:
        return link_haversine[d.index(min(d))]


def mapping_link(x,y):
    linked_haversine = link_haversine(geometry, x, y)
    return link_shortest(linked_haversine, geometry, x, y)

C:\Users\정현진\AppData\Local\Temp\ipykernel_11612\4205512960.py:6: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  geometry = geometry.str.replace('(','')
C:\Users\정현진\AppData\Local\Temp\ipykernel_11612\4205512960.py:7: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  geometry = geometry.str.replace(')','')

In [3]:
data = pd.read_csv('seoul_accident.csv', encoding='cp949')
latitude = data['위도']
longitude = data['경도']
lat_lon = []
for i in range(len(data)):
    lat_lon.append([longitude[i], latitude[i]])
drop_link = []
for i in range(0, 20):
    link_result = mapping_link(lat_lon[i][0], lat_lon[i][1])
    print(lat_lon[i][0], lat_lon[i][1])
    if link_result == None:
        drop_link.append(i) # csv 파일로는 + 2 
    if i % 1000 == 0:
        print("now : ", i)
with open('drop_link.txt', 'w') as f:
    for item in drop_link:
        f.write("%s " % item)

37.55366527 127.0416328
now :  0
37.6350152 127.0289101
37.5980603 126.9111043
37.460732 127.0355764
37.57502357 126.9804272
37.56117792 127.0359992
37.51860418 127.010339
37.5324982 126.9077717
37.6212959 127.0282476
37.5047531 127.1064263
37.4773468 126.898957
37.5884821 127.0940659
37.5874977 127.0942203
37.58052363 127.1865552
37.48213049 126.8862429
37.50847621 127.0164112
37.5225651 127.0373392
37.64686551 127.056571
37.52909453 127.0333702
37.5759036 127.1391282

In [5]:
with open('drop_link.txt', 'w') as f:
    for item in drop_link:
        f.write("%s\n" % item)

In [78]:
import pandas as pd

d = pd.read_csv("d.csv", encoding='utf-8')
arr = d['column'].values
for i in range(10):
    print(arr[i])

13
19
59
62
71
80
84
89
97
105

In [79]:
print(len(arr))

4036

In [80]:
data = pd.read_csv('seoul_accident.csv', encoding='cp949')
data.drop(arr, axis=0, inplace=True)

In [81]:
data = data.reset_index()
data = data.drop(['index'], axis=1)
data

,발생일시,경도,위도,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,2020-01-01 9:47,37.553665,127.041633,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-01-01 9:50,37.635015,127.028910,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-01-01 10:07,37.598060,126.911104,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-01-01 11:44,37.460732,127.035576,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-01-01 12:00,37.575024,126.980427,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
50296,2021-12-31 19:58,37.550049,127.122960,NaN,NaN,NaN,NaN,NaN,NaN
50297,2021-12-31 19:59,37.609281,127.072568,NaN,NaN,NaN,NaN,NaN,NaN
50298,2021-12-31 20:00,37.540529,126.939532,NaN,NaN,NaN,NaN,NaN,NaN
50299,2021-12-31 20:18,37.477067,126.981730,NaN,NaN,NaN,NaN,NaN,NaN
50300,2021-12-31 21:21,37.496387,127.091089,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data.to_csv('seoul_accident_drop.csv', encoding='cp949', index=False)